### ISSUE TITLE
Environment variables for commands

### ISSUE THREAD

**Issue by vokal-isaac** [vokal/XcodeAutoBasher#12]
It would be useful to have some or all of the run-script build phase environment variables available to the executables that are run in response to changes.

**Comment by designatednerd** [comment]
It certainly would be! How feasible is that?

**Comment by vokal-isaac** [comment]
The ones I really really want should be pretty feasible.  Getting all of them might be more of a challenge.  Feel free to assign this issue to me to at least do further research on, if not implement.  (And maybe tag as "enhancement"?)

**Comment by designatednerd** [comment]
Done!
