### ISSUE TITLE
Xcode Extension? 

### ISSUE THREAD

**Issue by designatednerd** [vokal/XcodeAutoBasher#24]
Would be nice to have add this as an Xcode extension for Xcode 8. Things to research: 

- [x] is this possible with System Integrity Protection? 
- [x] is this possible with what the process has access to? 
- [x] is this toast if we can't update it to an extension?

**Comment by vokal-isaac** [comment]
1. probably, up to issues with point 2.
2. my first guess from what was shown in the list of extendable things is no.
3. yes.  I'm pretty sure existing Xcode plugins are dead on Xcode 8.

**Comment by designatednerd** [comment]
I'll try to dig into some of the docs to find out.

**Comment by vokal-isaac** [comment]
Based on https://developer.apple.com/videos/play/wwdc2016/414/, I'm pretty sure the answer to 2 is ***no***.

**Comment by designatednerd** [comment]
Blech. Planning to watch that soonish and will file radars. In the meantime, I wonder if there's a way to do this that doesn't actually involve Xcode - we're only using Xcode for the plugin architecture and watching which projects are open - but I think we can watch the latter via notifications.

**Comment by designatednerd** [comment]
Blech. OK, so i think that leaves us at the point where we need to convert it to a standalone app. Boo-urns.

**Comment by tbodt** [comment]
Xcode plugins aren't completely dead on Xcode 8. You do, however, need to remove the code signature from Xcode to get them to load.

**Comment by designatednerd** [comment]
Yeah...I think I'd rather build a standalone mac app than remove the Xcode code signature, myself. 😄

**Comment by brockboland** [comment]
Updating documentation in #25

**Comment by designatednerd** [comment]
@brockboland @vokal-isaac Mind if I make a ticket to convert this to a mac app and then close this guy out?

**Comment by brockboland** [comment]
Works for me!

**Comment by designatednerd** [comment]
OK, not dead. #26 has been opened for converting to a mac app.

**Comment by ShengQiangLiu** [comment]
Remove the Xcode code signature，Is there any problem with this ?

**Comment by designatednerd** [comment]
@ShengQiangLiu: It leaves you vulnerable to things like [Xcode Ghost](https://en.wikipedia.org/wiki/XcodeGhost) and [Strawhorse](https://www.zdziarski.com/blog/?p=5040). I would very strongly advise against doing that.
