### ISSUE TITLE
add config for project

### ISSUE THREAD

**Issue by Whirlwind** [vokal/XcodeAutoBasher#6]
I hope this plugin will be able to read the config from project, so I can share the config to my team through the git or other subversion tools.

**Comment by designatednerd** [comment]
Hi @Whirlwind  - the plugin generates a `.plist` at the same level as your `xcodeproj` and/or `xcworkspace` that can then be checked into version control:  

![xcab_plist_ss](https://cloud.githubusercontent.com/assets/1976498/6669671/234529f8-cbc8-11e4-8f9c-c1f2a9b83c6c.png)

Anyone else running the plugin will be able to then have XcodeAutoBasher automatically pick up on that `plist` and run the scripts it's pointing to automatically.

**Comment by Whirlwind** [comment]
I am sorry.

**Comment by designatednerd** [comment]
No worries @Whirlwind - I'm making a note to add clearer documentation about this to the README.
